### ISSUE TITLE
ec2_group module: RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by jschaul** [ansible-collections/amazon.aws#161]
##### SUMMARY

`ec2_group` module fails with `RuntimeError: dictionary changed size during iteration` at `line 938, in get_final_rules` (i.e. in https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/cloud/amazon/ec2_group.py#L938-L940)

The problematic code can be found here also in ansible 2.9 stable: 

https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/cloud/amazon/ec2_group.py#L984-L986

```
                for k, v in format_rule['user_id_group_pairs'][0].items():
                    if v is None:
                        format_rule['user_id_group_pairs'][0].pop(k)
```

This modifies a dictionary while iterating over said dictionary, which is a forbidden operation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ec2_group.py` module

##### ANSIBLE VERSION

Affects ansible 2.7.x and 2.9.x as well. Tested on 2.7: (but the offending code remains in 2.9)

```paste below
ansible --version
ansible 2.7.18
  config file = REDACTED
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/xrasblmjvb8vk9by7cf5zakl0yafd349-python3.7-ansible-2.7.18/lib/python3.7/site-packages/ansible
  executable location = /nix/store/xrasblmjvb8vk9by7cf5zakl0yafd349-python3.7-ansible-2.7.18/bin/ansible
  python version = 3.7.8 (default, Jun 27 2020, 09:38:56) [GCC 9.3.0
```

##### OS / ENVIRONMENT

Any version of linux. (fails on localhost on fedora 32 as an example)

##### STEPS TO REPRODUCE

A custom module calling ec2_group on AWS EC2 Classic (no VPC involved).

```
            module_return = self._execute_module(module_name='ec2_group',
                                                 module_args=sg_args,
                                                 task_vars=task_vars,
                                                 tmp=tmp)
```

It's not easily reproducible for an outsider without access to AWS EC2 Classic, however the three lines of code quoted above are clearly problematic and can be run in isolation:

```py
# example.py

format_rule = {}
format_rule['user_id_group_pairs'] = [{
    'description': "hello",
    'group_id': "1234",
    'group_name': "hello",
    'peering_status': None,
    'user_id': "user123",
    'vpc_id': None,
    'vpc_peering_connection_id': None
}]
for k, v in format_rule['user_id_group_pairs'][0].items():
    if v is None:
        format_rule['user_id_group_pairs'][0].pop(k)
```

Run `python example.py` (python --version
`Python 3.8.5`) leads to 

```
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    for k, v in format_rule['user_id_group_pairs'][0].items():
RuntimeError: dictionary changed size during iteration
```

Note: Originally filed in https://github.com/ansible/ansible/issues/71698

**Comment by tremble** [comment]
Thank you for taking the time to raise this issue.

This issue was originally filed as https://github.com/ansible/ansible/issues/56902 and is fixed by https://github.com/ansible/ansible/pull/56903 which is available in both Ansible 2.9 and this collection (which will be available with Ansible 2.10)

The code you referenced for Ansible 2.9 is subtly different:

`for k, v in list(format_rule['user_id_group_pairs'][0].items()):`

The items() is explicitly loaded into a temporary list which is iterated over, rather than directly iterating through the dictionary.

At this point Ansible 2.7 is no longer maintained and Ansible 2.8 only receives security fixes ([Release and maintenance policy](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html
)) as such I'm going to close out this issue.
