### ISSUE TITLE
Bad Unit Test for Shippable, blocking simple PR for documentation update

### ISSUE THREAD

**Issue by johnpetersjr** [ansible-collections/amazon.aws#68]
Unit tests ran on my PR to fix some documentation links:
https://app.shippable.com/github/ansible-collections/amazon.aws/runs/270/summary/console

It found issues with these lines/plays:

https://github.com/ansible-collections/amazon.aws/blob/629b890ed6266f19f92c76288cd1a2f095d96e2e/tests/integration/targets/aws_s3/tasks/main.yml#L494

https://github.com/ansible-collections/amazon.aws/blob/629b890ed6266f19f92c76288cd1a2f095d96e2e/tests/integration/targets/aws_s3/tasks/main.yml#L505

How can these two exact same plays in a test case have different results?  (result is changed, and is not changed, with the same criteria on deleting a bucket.bucket?)  Seems like a change is needed on the test cases here?

**Comment by tremble** [comment]
Hi @johnpetersjr thanks for taking the time to update the documentation and raise this bug.

In this particular case the tests aren't wrong.  These are integration tests, not unit tests.  The tests created a bucket, made some changes, the task at line 494 resulted in the bucket being deleted (this was is change, so `result is changed`), then when the delete is re-run the bucket should already have been deleted, so nothing should happen (ie `result is not changed`).

These tests are fairly standard within our integration tests, we're testing that module operations are idempotent.  https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#term-idempotency


The issue you hit in that failed test is actually a race condition rather than a bad test: On the second run it checked to see if the bucket still existed, which it did, (the deletion's was requested, but the deletion hadn't happened yet), and then tried to delete the bucket, only to be told "bucket already deleted".  There's a bug here, in that the race condition wasn't properly handled, but it's not the bug you thought it was.
